# Generated by Django 5.0.1 on 2025-05-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_playlist_playlistsong'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
